name = "cf-agri-dashboard"
compatibility_date = "2024-03-20"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "agri-db"
database_id = "18722ebf-2f7b-4f67-b7f7-2bab869e72bf" 
